name: 'DBT_Pr_UFA'

version: '1.8.0'

config-version: 2

profile: 'redshift'

snapshots:
  DBT_Pr_UFA:            # your dbt project name
    +target_schema: snapshots
    +path: snapshots

vars:
  start_date: '2024-01-01'