models:
  - name: hrtg_customers
    columns:
      - name: id
        tests:
          - not_null
          - unique
  
  - name: hrtg_products
    columns:
      - name: id
        tests:
          - not_null
          - unique